services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: ticketing-backend

    ports:
      - "8001:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"