services:

  ticket-be:
    image: ticket-be:latest
    container_name: ticket-be
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "8000"
    networks:
      - ticket-private-network

  ticket-worker:
    image: ticket-be:latest
    container_name: ticket-worker
    restart: unless-stopped
    env_file:
      - .env
    command: ["python", "-m", "app.jobs.worker"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ticket-private-network

  ticket-fe:
    image: ticket-fe:latest
    container_name: ticket-fe
    restart: unless-stopped

    expose:
      - "3000"

    depends_on:
      - ticket-be

    networks:
      - ticket-private-network

networks:
  ticket-private-network:
    external: true