"""initial ticket management schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB
revision = "0001_initial"; down_revision = None; branch_labels = None; depends_on = None
def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    uuid = lambda: sa.Column("id", UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True)
    op.create_table("users", uuid(), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("full_name", sa.String(200), nullable=False), sa.Column("password_hash", sa.Text, nullable=False), sa.Column("role", sa.String(20), nullable=False, server_default="CUSTOMER"), sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("refresh_tokens", uuid(), sa.Column("user_id", UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False, unique=True), sa.Column("family_id", UUID(as_uuid=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("revoked_at", sa.DateTime(timezone=True)), sa.Column("used_at", sa.DateTime(timezone=True)))
    op.create_table("tickets", uuid(), sa.Column("ticket_number", sa.String(20), nullable=False, unique=True), sa.Column("title", sa.String(300), nullable=False), sa.Column("description", sa.Text, nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="OPEN"), sa.Column("priority", sa.String(5), nullable=False, server_default="P3"), sa.Column("category", sa.String(50)), sa.Column("customer_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("assignee_id", UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("created_by", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("comments", uuid(), sa.Column("ticket_id", UUID(as_uuid=True), sa.ForeignKey("tickets.id", ondelete="CASCADE"), nullable=False), sa.Column("author_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("body", sa.Text, nullable=False), sa.Column("is_internal", sa.Boolean, nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("sla_policies", uuid(), sa.Column("name", sa.String(100), unique=True, nullable=False), sa.Column("priority", sa.String(5), nullable=False), sa.Column("first_response_minutes", sa.Integer, nullable=False), sa.Column("resolution_hours", sa.Integer, nullable=False), sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("ticket_sla", uuid(), sa.Column("ticket_id", UUID(as_uuid=True), sa.ForeignKey("tickets.id"), unique=True, nullable=False), sa.Column("policy_id", UUID(as_uuid=True), sa.ForeignKey("sla_policies.id"), nullable=False), sa.Column("first_response_due_at", sa.DateTime(timezone=True)), sa.Column("resolution_due_at", sa.DateTime(timezone=True)), sa.Column("first_responded_at", sa.DateTime(timezone=True)), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.Column("breached_at", sa.DateTime(timezone=True)), sa.Column("status", sa.String(20), server_default="ACTIVE"))
    op.create_table("notifications", uuid(), sa.Column("recipient_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("ticket_id", UUID(as_uuid=True), sa.ForeignKey("tickets.id")), sa.Column("template_key", sa.String(50), nullable=False), sa.Column("channel", sa.String(20), server_default="EMAIL"), sa.Column("subject", sa.Text, nullable=False), sa.Column("body", sa.Text, nullable=False), sa.Column("status", sa.String(20), server_default="PENDING"), sa.Column("sent_at", sa.DateTime(timezone=True)))
    op.create_table("audit_logs", uuid(), sa.Column("actor_id", UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("action", sa.String(100), nullable=False), sa.Column("entity_type", sa.String(50), nullable=False), sa.Column("entity_id", UUID(as_uuid=True)), sa.Column("old_values", JSONB), sa.Column("new_values", JSONB), sa.Column("correlation_id", UUID(as_uuid=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.execute("INSERT INTO sla_policies (name, priority, first_response_minutes, resolution_hours) VALUES ('P1 default','P1',30,4),('P2 default','P2',120,8),('P3 default','P3',480,24),('P4 default','P4',1440,72) ON CONFLICT (name) DO NOTHING")
def downgrade():
    for table in ("audit_logs", "notifications", "ticket_sla", "sla_policies", "comments", "tickets", "refresh_tokens", "users"): op.drop_table(table)
