const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api/v1';
const getTokens = () => { if (typeof window === 'undefined') return {}; return { access: localStorage.getItem('access_token'), refresh: localStorage.getItem('refresh_token') }; };
const saveTokens = (data) => { localStorage.setItem('access_token', data.access_token); localStorage.setItem('refresh_token', data.refresh_token); };
async function request(path, options = {}, retry = true) {
  const headers = { 'Content-Type':'application/json', ...(options.headers || {}) }; const { access } = getTokens(); if (access) headers.Authorization = `Bearer ${access}`;
  const response = await fetch(`${API_URL}${path}`, { ...options, headers });
  if (response.status === 401 && retry && getTokens().refresh) { const refreshed = await fetch(`${API_URL}/auth/refresh`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({refresh_token:getTokens().refresh}) }); if (refreshed.ok) { saveTokens(await refreshed.json()); return request(path, options, false); } }
  if (!response.ok) { let body; try { body = await response.json(); } catch {} throw new Error(body?.error?.message || `Request failed (${response.status})`); }
  if (response.status === 204) return null; return response.json();
}
export const api = { request, login:(data)=>request('/auth/login',{method:'POST',body:JSON.stringify(data)},false), register:(data)=>request('/auth/register',{method:'POST',body:JSON.stringify(data)},false), me:()=>request('/auth/me'), logout:()=>request('/auth/logout',{method:'POST',body:JSON.stringify({refresh_token:getTokens().refresh})}), tickets:(query='')=>request(`/tickets${query}`), ticket:(id)=>request(`/tickets/${id}`), createTicket:(data)=>request('/tickets',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(data)}), updateStatus:(id,status)=>request(`/tickets/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}), comments:(id)=>request(`/tickets/${id}/comments`), addComment:(id,data)=>request(`/tickets/${id}/comments`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(data)}), users:()=>request('/users'), role:(id,role)=>request(`/users/${id}/role`,{method:'PATCH',body:JSON.stringify({role})}), policies:()=>request('/sla/policies'), createPolicy:(data)=>request('/sla/policies',{method:'POST',body:JSON.stringify(data)}), audit:(query='')=>request(`/audit/logs${query}`) };
export { getTokens, saveTokens, API_URL };
