"""Permission catalog and default role mappings."""

PERMISSIONS = [
    "ticket.view",
    "ticket.view_own",
    "ticket.create",
    "ticket.update",
    "ticket.assign",
    "ticket.delete",
    "ticket.merge",
    "ticket.escalate",
    "ticket.transition",
    "comment.public.write",
    "comment.internal.read",
    "comment.internal.write",
    "sla.view",
    "sla.manage",
    "sla.override",
    "user.manage",
    "team.manage",
    "queue.manage",
    "report.view",
    "report.export",
    "audit.view",
    "settings.manage",
    "organization.manage",
    "contact.manage",
    "automation.manage",
    "kb.manage",
    "kb.view",
    "notification.manage",
    "event.view",
    "event.admin",
]

DEFAULT_ROLES: dict[str, list[str]] = {
    "OWNER": PERMISSIONS,
    "ADMIN": [
        p for p in PERMISSIONS if p not in ("sla.override",)
    ],
    "SUPERVISOR": [
        "ticket.view",
        "ticket.create",
        "ticket.update",
        "ticket.assign",
        "ticket.transition",
        "comment.public.write",
        "comment.internal.read",
        "comment.internal.write",
        "sla.view",
        "sla.override",
        "team.manage",
        "queue.manage",
        "report.view",
        "report.export",
        "audit.view",
        "organization.manage",
        "contact.manage",
        "automation.manage",
        "kb.manage",
        "kb.view",
        "notification.manage",
    ],
    "AGENT": [
        "ticket.view",
        "ticket.create",
        "ticket.update",
        "ticket.assign",
        "ticket.transition",
        "comment.public.write",
        "comment.internal.read",
        "comment.internal.write",
        "sla.view",
        "report.view",
        "kb.view",
        "kb.manage",
    ],
    "CUSTOMER": [
        "ticket.view_own",
        "ticket.create",
        "comment.public.write",
        "kb.view",
    ],
    "CUSTOMER_ADMIN": [
        "ticket.view_own",
        "ticket.create",
        "comment.public.write",
        "contact.manage",
        "kb.view",
    ],
}

# Legacy role mapping for backward compatibility during migration
LEGACY_ROLE_MAP = {
    "ADMIN": "ADMIN",
    "AGENT": "AGENT",
    "CUSTOMER": "CUSTOMER",
}
